### ISSUE TITLE
Missing fonts in Native App Builder

### ISSUE THREAD

**Issue by apemberton** [apemberton/outsystems-studio-mac#9]
<img width="371" alt="screen shot 2018-04-08 at 8 16 51 am" src="https://user-images.githubusercontent.com/86439/38467356-35aef6be-3b05-11e8-8d9d-e0e6c3b79b4f.png">

**Comment by apemberton** [comment]
Should be addressed in https://github.com/apemberton/outsystems-studio-mac/releases/tag/0.9

**Comment by goborrega** [comment]
The example above looks good in this version.
But I still see wrong fonts on the Aggregates. New issue/new font?
![image](https://user-images.githubusercontent.com/2310518/38470698-a252fef6-3b5e-11e8-9a46-01e2df612852.png)

**Comment by apemberton** [comment]
Not sure. Will check. Do we know the full list of all fonts used in studio?

**Comment by apemberton** [comment]
This font should now be Open Sans (almost same as Segoe UI).
